# This is a basic workflow to help you get started with Actions

name: File_types

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - check_branch1

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Install dockerize
      run: |
        wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
      env:
        DOCKERIZE_VERSION: v0.3.0

    - name: Kubernetes CLI - kubectl
      uses: steebchen/kubectl@v1.0.0

    - id: file_changes
      uses: trilom/file-changes-action@v1.2.3
    - name: List all file changes
      run: |
        ls
        all_files_arr=${{ steps.file_changes.outputs.files}}
        echo "All files below :"
        echo $all_files_arr|tr -d "[]\"" |tr "," "\n"
        php_file_count=`echo $all_files_arr|tr -d "[]\"" |tr "," "\n"|grep -c "\.php$" || true`
        if [ "$php_file_count"  -eq "0" ];then
              echo "No PHP files found, skipping image creation."
        else
              echo "PHP files found, starting image creation."
        fi
