# This is a basic workflow to help you get started with Actions

name: File_types

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - check_branch1

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell

    - id: file_changes
      uses: trilom/file-changes-action@v1.2.3
    - name: List all file changes
      run: |
        all_files_arr=`echo '${{ steps.file_changes.outputs.files}}'`
        echo $all_files_arr|tr -d "[]\"" |tr "," "\n"|grep "\.php$"
        php_files=`echo $all_files_arr|tr -d "[]\"" |tr "," "\n"|grep "\.php$"`
        echo "PHP Files : "$php_files
        php_file_count=`echo $php_files|wc -l`
        if [ -z "$php_file_count" ];then
              echo "No PHP files found, skipping image creation."
        else
              echo "PHP files found, starting image creation."
        fi
